[pytest]
testpaths = tests
norecursedirs =
    .git
    .idea
    .venv
    clone
    data
    reports
    repoinsight.egg-info
    __pycache__
    pytest-cache-files-*
python_files = test_*.py
cache_dir = .pytest_cache
